using System.Text;
using System.Text.Json;

namespace X4MP.Protocol.Tests;

/// <summary>
/// The shared mod-policy constants (M1-X1) live once in <c>protocol/constants/mod_policy.json</c>. This generator writes
/// the C# (<c>ModPolicyConstants.g.cs</c>) and C++ (<c>mod_policy_constants.h</c>) forms; the tests fail when either
/// committed file drifts from the JSON, and compare the compiled C# values with the JSON. The C++ test suite checks the
/// header against the same JSON. Regenerate with <c>X4MP_UPDATE_GOLDEN=1 dotnet test --filter ModPolicyConstantsTests</c>.
/// </summary>
public class ModPolicyConstantsTests
{
    private static string RepoRoot
    {
        get
        {
            var dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, "protocol", "schema")))
            {
                dir = dir.Parent;
            }

            return dir?.FullName ?? throw new InvalidOperationException("repo root not found");
        }
    }

    private static string JsonPath => Path.Combine(RepoRoot, "protocol", "constants", "mod_policy.json");

    private static string CsPath => Path.Combine(RepoRoot, "server", "src", "X4MP.Protocol", "ModPolicyConstants.g.cs");

    private static string CppPath => Path.Combine(RepoRoot, "protocol", "cpp", "include", "x4mp", "mod_policy_constants.h");

    private static JsonElement Load() => JsonDocument.Parse(File.ReadAllText(JsonPath)).RootElement;

    private static string Esc(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n");

    private static string[] Strings(JsonElement root, string name) => root.GetProperty(name).EnumerateArray().Select(e => e.GetString()!).ToArray();

    public static string GenerateCSharp(JsonElement r)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n// Generated from protocol/constants/mod_policy.json by X4MP.Protocol.Tests ModPolicyConstantsTests. Do not edit.\n// </auto-generated>\n");
        sb.Append("namespace X4MP.Protocol;\n\n/// <summary>Shared mod-policy constants (docs/mod-management.md); same values as the C++ header mod_policy_constants.h.</summary>\n");
        sb.Append("public static class ModPolicyConstants\n{\n");
        sb.Append("    /// <summary>Client-only library allowlist (ADR-043): never in the extensions hash, never rejected.</summary>\n");
        sb.Append("    public static readonly string[] ClientOnlyLibraryIds = [").Append(string.Join(", ", Strings(r, "clientOnlyLibraryIds").Select(s => $"\"{Esc(s)}\""))).Append("];\n\n");
        sb.Append("    /// <summary>Compared through version fields and excluded from the hash (x4native, x4mp).</summary>\n");
        sb.Append("    public static readonly string[] HashExcludedIds = [").Append(string.Join(", ", Strings(r, "hashExcludedIds").Select(s => $"\"{Esc(s)}\""))).Append("];\n\n");
        foreach (var (json, name) in new[]
        {
            ("dlcIdPrefix", "DlcIdPrefix"), ("workshopIdPrefix", "WorkshopIdPrefix"), ("nexusUrlRegex", "NexusUrlRegex"), ("nexusUrlFormat", "NexusUrlFormat"),
            ("workshopUrlFormat", "WorkshopUrlFormat"), ("workshopSteamUrlFormat", "WorkshopSteamUrlFormat"), ("hashLineFormat", "HashLineFormat"),
        })
        {
            sb.Append("    public const string ").Append(name).Append(" = \"").Append(Esc(r.GetProperty(json).GetString()!)).Append("\";\n\n");
        }

        sb.Append("    public const int MaxExtensionEntries = ").Append(r.GetProperty("maxExtensionEntries").GetInt32()).Append(";\n}\n");
        return sb.ToString();
    }

    public static string GenerateCpp(JsonElement r)
    {
        var sb = new StringBuilder();
        sb.Append("// Generated from protocol/constants/mod_policy.json by X4MP.Protocol.Tests ModPolicyConstantsTests. Do not edit.\n");
        sb.Append("// Shared mod-policy constants (docs/mod-management.md); same values as C# X4MP.Protocol.ModPolicyConstants.\n#pragma once\n\n#include <array>\n#include <string_view>\n\nnamespace x4mp::mod_policy {\n\n");
        var allow = Strings(r, "clientOnlyLibraryIds");
        sb.Append("inline constexpr std::array<std::string_view, ").Append(allow.Length).Append("> kClientOnlyLibraryIds{").Append(string.Join(", ", allow.Select(s => $"\"{Esc(s)}\""))).Append("};\n");
        var excl = Strings(r, "hashExcludedIds");
        sb.Append("inline constexpr std::array<std::string_view, ").Append(excl.Length).Append("> kHashExcludedIds{").Append(string.Join(", ", excl.Select(s => $"\"{Esc(s)}\""))).Append("};\n");
        foreach (var (json, name) in new[]
        {
            ("dlcIdPrefix", "kDlcIdPrefix"), ("workshopIdPrefix", "kWorkshopIdPrefix"), ("nexusUrlRegex", "kNexusUrlRegex"), ("nexusUrlFormat", "kNexusUrlFormat"),
            ("workshopUrlFormat", "kWorkshopUrlFormat"), ("workshopSteamUrlFormat", "kWorkshopSteamUrlFormat"), ("hashLineFormat", "kHashLineFormat"),
        })
        {
            sb.Append("inline constexpr std::string_view ").Append(name).Append(" = \"").Append(Esc(r.GetProperty(json).GetString()!)).Append("\";\n");
        }

        sb.Append("inline constexpr int kMaxExtensionEntries = ").Append(r.GetProperty("maxExtensionEntries").GetInt32()).Append(";\n\n}  // namespace x4mp::mod_policy\n");
        return sb.ToString();
    }

    private static string Normalise(string s) => s.Replace("\r\n", "\n");

    [Fact]
    public void GeneratedFilesMatchTheJsonSource()
    {
        var root = Load();
        if (Environment.GetEnvironmentVariable("X4MP_UPDATE_GOLDEN") == "1")
        {
            File.WriteAllText(CsPath, GenerateCSharp(root), new UTF8Encoding(false));
            File.WriteAllText(CppPath, GenerateCpp(root), new UTF8Encoding(false));
            return;
        }

        Assert.True(File.Exists(CsPath) && File.Exists(CppPath), "generated constants missing; regenerate with X4MP_UPDATE_GOLDEN=1");
        Assert.Equal(GenerateCSharp(root), Normalise(File.ReadAllText(CsPath)));
        Assert.Equal(GenerateCpp(root), Normalise(File.ReadAllText(CppPath)));
    }

    [Fact]
    public void CompiledCSharpValuesEqualTheJson()
    {
        var r = Load();
        Assert.Equal(Strings(r, "clientOnlyLibraryIds"), ModPolicyConstants.ClientOnlyLibraryIds);
        Assert.Equal(Strings(r, "hashExcludedIds"), ModPolicyConstants.HashExcludedIds);
        Assert.Equal(ModPolicyConstants.DlcIdPrefix, r.GetProperty("dlcIdPrefix").GetString());
        Assert.Equal(ModPolicyConstants.WorkshopIdPrefix, r.GetProperty("workshopIdPrefix").GetString());
        Assert.Equal(ModPolicyConstants.NexusUrlRegex, r.GetProperty("nexusUrlRegex").GetString());
        Assert.Equal(ModPolicyConstants.NexusUrlFormat, r.GetProperty("nexusUrlFormat").GetString());
        Assert.Equal(ModPolicyConstants.WorkshopUrlFormat, r.GetProperty("workshopUrlFormat").GetString());
        Assert.Equal(ModPolicyConstants.WorkshopSteamUrlFormat, r.GetProperty("workshopSteamUrlFormat").GetString());
        Assert.Equal(ModPolicyConstants.HashLineFormat, r.GetProperty("hashLineFormat").GetString());
        Assert.Equal(ModPolicyConstants.MaxExtensionEntries, r.GetProperty("maxExtensionEntries").GetInt32());
    }
}
