using System.Text.Json;
using System.Text.Json.Serialization;

namespace X4MP.Server.Api;

/// <summary>Source-generated JSON metadata for admin API DTOs (camelCase, server-design 4.1).</summary>
[JsonSourceGenerationOptions(JsonSerializerDefaults.Web)]
[JsonSerializable(typeof(HealthzResponse))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(MeDto))]
[JsonSerializable(typeof(ApiProblem))]
[JsonSerializable(typeof(SettingsSchemaDto))]
[JsonSerializable(typeof(SettingsDto))]
[JsonSerializable(typeof(List<MetricSeriesDto>))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(ServerInfoDto))]
[JsonSerializable(typeof(DashboardSnapshotDto))]
[JsonSerializable(typeof(SessionDetailDto))]
[JsonSerializable(typeof(List<SessionSummaryDto>))]
[JsonSerializable(typeof(List<SessionEventDto>))]
[JsonSerializable(typeof(CreateSessionRequest))]
[JsonSerializable(typeof(StartSessionRequest))]
[JsonSerializable(typeof(StopSessionRequest))]
[JsonSerializable(typeof(List<PlayerDto>))]
[JsonSerializable(typeof(PlayerDto))]
[JsonSerializable(typeof(PlayerDetailDto))]
[JsonSerializable(typeof(KickRequest))]
[JsonSerializable(typeof(MuteRequest))]
[JsonSerializable(typeof(PatchPlayerRequest))]
[JsonSerializable(typeof(List<BanDto>))]
[JsonSerializable(typeof(BanDto))]
[JsonSerializable(typeof(CreateBanRequest))]
[JsonSerializable(typeof(List<ChatMessageDto>))]
[JsonSerializable(typeof(SendChatRequest))]
[JsonSerializable(typeof(ChatSentDto))]
[JsonSerializable(typeof(List<LogEntryDto>))]
[JsonSerializable(typeof(List<ConnectionStatsDto>))]
[JsonSerializable(typeof(TraceRequest))]
[JsonSerializable(typeof(List<ApiTokenDto>))]
[JsonSerializable(typeof(CreateTokenRequest))]
[JsonSerializable(typeof(ApiTokenCreatedDto))]
[JsonSerializable(typeof(List<AuditEntryDto>))]
[JsonSerializable(typeof(GalaxyDto))]
[JsonSerializable(typeof(SectorDetailDto))]
[JsonSerializable(typeof(PlayerLiveDto))]
[JsonSerializable(typeof(SessionSummaryDto))]
[JsonSerializable(typeof(GalaxyFrameDto))]
[JsonSerializable(typeof(SectorFrameDto))]
[JsonSerializable(typeof(ChatMessageDto))]
[JsonSerializable(typeof(TransferProgressDto))]
[JsonSerializable(typeof(AlertDto))]
[JsonSerializable(typeof(PermissionDeniedDto))]
[JsonSerializable(typeof(LogFilterDto))]
internal sealed partial class ApiJsonContext : JsonSerializerContext;
