// X4Native extension entry point for x4mp.dll. Thin on purpose: it creates the ModHost (host/mod_host.h, which
// documents the full DLL lifecycle contract) and forwards X4Native events to it. All behaviour lives in host/ and
// features/ (add a feature in host/feature_list.cpp, not here). With game/x4_platform.cpp this is the only code that
// sees the X4Native SDK.
//
// Exports (generated by the macros): x4native_api_version, x4native_init, x4native_shutdown. Neither init nor
// shutdown throws. A reload is x4native_shutdown() followed by x4native_init() on the same loaded DLL with the
// X4Native stash kept; all state here is process-static and fully reset by shutdown.

#include <array>
#include <memory>

#include <x4n_core.h>
#include <x4n_events.h>

#include "game/x4_platform.h"
#include "host/mod_host.h"

namespace {
std::unique_ptr<x4mp::game::X4Platform> g_platform;
std::unique_ptr<x4mp::host::ModHost> g_host;
std::array<int, 4> g_subscriptions{};
std::size_t g_subscription_count = 0;

void ev_frame() {
  if (g_host) g_host->on_frame();
}
void ev_game_loaded() {
  if (g_host) g_host->on_game_loaded();
}
void ev_universe_ready() {
  if (g_host) g_host->on_universe_ready();
}
void ev_ui_reload() {
  if (g_host) g_host->on_ui_reload();
}

void subscribe(const char* name, void (*fn)()) {
  const int id = x4n::on(name, fn);
  if (id > 0 && g_subscription_count < g_subscriptions.size()) g_subscriptions[g_subscription_count++] = id;
}
}  // namespace

X4N_EXTENSION {
  try {
    g_platform = std::make_unique<x4mp::game::X4Platform>();
    g_host = std::make_unique<x4mp::host::ModHost>(*g_platform);
    if (g_host->init() == x4mp::host::InitResult::Started) {
      subscribe("on_frame_update", &ev_frame);
      subscribe("on_game_loaded", &ev_game_loaded);
      subscribe("on_universe_ready", &ev_universe_ready);
      subscribe("on_ui_reload", &ev_ui_reload);
    }
    // Refused: the host logged why and stays inert; we still return OK so X4Native keeps running normally.
  } catch (...) {
    // Never throw into X4Native.
  }
}

X4N_SHUTDOWN {
  try {
    for (std::size_t i = 0; i < g_subscription_count; ++i) x4n::off(g_subscriptions[i]);
    g_subscription_count = 0;
    if (g_host) g_host->shutdown();  // feature on_shutdown, stash state, log flush (needs the API pointer, still set)
    if (g_platform) g_platform->clear_lua_verbs();  // Lua verbs (x4mp.join ...): no handler runs after this
    g_host.reset();
    g_platform.reset();
  } catch (...) {
  }
}
