// <auto-generated>
// Generated from protocol/constants/mod_policy.json by X4MP.Protocol.Tests ModPolicyConstantsTests. Do not edit.
// </auto-generated>
namespace X4MP.Protocol;

/// <summary>Shared mod-policy constants (docs/mod-management.md); same values as the C++ header mod_policy_constants.h.</summary>
public static class ModPolicyConstants
{
    /// <summary>Client-only library allowlist (ADR-043): never in the extensions hash, never rejected.</summary>
    public static readonly string[] ClientOnlyLibraryIds = ["kuerteeUIExtensionsAndHUD", "ws_3477279743", "ws_2042901274", "ws_3514258146"];

    /// <summary>Compared through version fields and excluded from the hash (x4native, x4mp).</summary>
    public static readonly string[] HashExcludedIds = ["x4native", "x4mp"];

    public const string DlcIdPrefix = "ego_dlc_";

    public const string WorkshopIdPrefix = "ws_";

    public const string NexusUrlRegex = "^https://(www\\.)?nexusmods\\.com/x4foundations/mods/(\\d+)(/.*)?$";

    public const string NexusUrlFormat = "https://www.nexusmods.com/x4foundations/mods/{0}";

    public const string WorkshopUrlFormat = "https://steamcommunity.com/sharedfiles/filedetails/?id={0}";

    public const string WorkshopSteamUrlFormat = "steam://url/CommunityFilePage/{0}";

    public const string HashLineFormat = "{id}@{version}\n";

    public const int MaxExtensionEntries = 1000;
}
