using System.Collections;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using X4MP.Server.Api;

namespace X4MP.TsContract;

/// <summary>
/// Reflects over <see cref="TsContractAttribute"/>-marked DTOs and enums and emits TypeScript declarations
/// (server-design 4.1). Output is deterministic: types are ordered by name, LF line endings, camelCase members
/// (matching the server's <c>JsonSerializerDefaults.Web</c>), enums as string unions.
/// </summary>
public static class TsContractGenerator
{
    public const string Header =
        "// This file is generated by tools/X4MP.TsContractGenerator from the [TsContract] types in X4MP.Server.\n" +
        "// Do not edit by hand. Regenerate with: dotnet run --project tools/X4MP.TsContractGenerator\n";

    /// <summary>Generates the contract for every <c>[TsContract]</c> type in the assembly of <see cref="TsContractAttribute"/>.</summary>
    public static string Generate() => Generate(typeof(TsContractAttribute).Assembly.GetTypes());

    public static string Generate(IEnumerable<Type> candidates)
    {
        ArgumentNullException.ThrowIfNull(candidates);
        var types = candidates
            .Where(t => t.GetCustomAttribute<TsContractAttribute>() is not null)
            .OrderBy(t => t.Name, StringComparer.Ordinal)
            .ToList();
        var marked = types.ToHashSet();

        var sb = new StringBuilder(Header);
        if (types.Count == 0)
        {
            sb.Append("\nexport {};\n");
            return sb.ToString();
        }

        foreach (var type in types)
        {
            sb.Append('\n');
            if (type.IsEnum)
            {
                var names = Enum.GetNames(type).Select(n => "'" + n + "'");
                sb.Append("export type ").Append(type.Name).Append(" = ").Append(string.Join(" | ", names)).Append(";\n");
                continue;
            }

            sb.Append("export interface ").Append(type.Name).Append(" {\n");
            var nullability = new NullabilityInfoContext();
            foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                         .Where(p => p.GetIndexParameters().Length == 0 && p.GetCustomAttribute<JsonIgnoreAttribute>() is null)
                         .OrderBy(p => p.MetadataToken))
            {
                var name = property.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name
                    ?? JsonNamingPolicy.CamelCase.ConvertName(property.Name);
                var info = nullability.Create(property);
                var nullable = info.ReadState == NullabilityState.Nullable || Nullable.GetUnderlyingType(property.PropertyType) is not null;
                var tsType = Map(Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType, marked, $"{type.Name}.{property.Name}");
                sb.Append("  ").Append(name).Append(": ").Append(tsType).Append(nullable ? " | null" : string.Empty).Append(";\n");
            }
            sb.Append("}\n");
        }
        return sb.ToString();
    }

    private static string Map(Type type, HashSet<Type> marked, string where)
    {
        if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(TimeSpan))
        {
            return "string";
        }
        if (type == typeof(bool))
        {
            return "boolean";
        }
        if (type == typeof(byte) || type == typeof(sbyte) || type == typeof(short) || type == typeof(ushort)
            || type == typeof(int) || type == typeof(uint) || type == typeof(long) || type == typeof(ulong)
            || type == typeof(float) || type == typeof(double) || type == typeof(decimal))
        {
            return "number";
        }
        if (type == typeof(object) || type == typeof(JsonElement))
        {
            return "unknown";
        }
        if (type.IsArray)
        {
            return Wrap(Map(type.GetElementType()!, marked, where)) + "[]";
        }
        if (type.IsGenericType)
        {
            var definition = type.GetGenericTypeDefinition();
            var args = type.GetGenericArguments();
            if (definition == typeof(Dictionary<,>) || definition == typeof(IDictionary<,>) || definition == typeof(IReadOnlyDictionary<,>))
            {
                if (args[0] != typeof(string))
                {
                    throw new NotSupportedException($"{where}: dictionary keys must be strings.");
                }
                return "Record<string, " + Map(args[1], marked, where) + ">";
            }
            if (args.Length == 1 && typeof(IEnumerable).IsAssignableFrom(type))
            {
                return Wrap(Map(args[0], marked, where)) + "[]";
            }
        }
        if (marked.Contains(type))
        {
            return type.Name;
        }
        throw new NotSupportedException($"{where}: type {type.FullName} is not supported; mark it [TsContract] or use a supported type.");
    }

    private static string Wrap(string tsType) => tsType.Contains(' ', StringComparison.Ordinal) ? "(" + tsType + ")" : tsType;
}
