<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\X4MP.Core\X4MP.Core.csproj" />
  </ItemGroup>

</Project>
